### ISSUE TITLE
Chapter 6 - server not allowing authentication

### ISSUE THREAD

**Issue by MichaelFromin** [Akryum/packt-vue-project-guide#1]
I setup the credentials as instructed and I enter my Google details in the popup but instead of getting redirected to the app I get this in the popup:

```
Error
    at /Users/mfromin/mean-web-dev/vue-projects-packt/server-geoblog/node_modules/passport-google-oauth20/lib/strategy.js:95:21
    at passBackControl (/Users/mfromin/mean-web-dev/vue-projects-packt/server-geoblog/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/mfromin/mean-web-dev/vue-projects-packt/server-geoblog/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
The URL in the popup when this happens is:

```
http://localhost:3000/auth/google/callback?code=4/DDxip_0uuyGrCEgrxdaAhVlnTc76tIpG0LNOhk8fmAk&authuser=0&session_state=3ba636c9e4c4544776e49314343084acbca54cea..6e85&prompt=none#
```
Any idea what would cause this?

**Comment by MichaelFromin** [comment]
This turned out to be that I did not enable the Google+ API ... I missed that in the list of things to do when setting up the account.  Apologies.
